version: '3.8'

services:

  frontend:

    image: 'githinji4gibson/frontend:latest'

    ports:
      - "3000:3000"

    volumes:
      - type: bind

        source : ./nginx/default.conf

        target: /etc/nginx/conf.d/default.conf

  backend:

    image: 'githinji4gibson/backendapi:latest'

    ports:
      - "8000:8000"

    command: python manage.py runserver





