version: '3.8'

services:

  frontend:

    image: 'githinji4gibson/frontend:latest'

    ports:
      - "80:80"

    volumes:
      - type: bind

        source : ./nginx/default.conf

        target: /etc/nginx/conf.d/default.conf

    restart: always

  backend:

    image: 'githinji4gibson/backendapi:latest'

    expose:
      - 8000

    command: python manage.py runserver 0.0.0.0:8000

    restart: always





